// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Content from "./islands/Content.tsx";
import * as $Countdown from "./islands/Countdown.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $WhatsNextCard from "./islands/WhatsNextCard.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Content.tsx": $Content,
    "./islands/Countdown.tsx": $Countdown,
    "./islands/Hero.tsx": $Hero,
    "./islands/WhatsNextCard.tsx": $WhatsNextCard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
