// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$1 from "./loaders/availableIcons.ts";
import * as $$$2 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/unbank/loaders/availableIcons.ts": $$$1,
    "deco-sites/unbank/loaders/icons.ts": $$$2,
    "deco-sites/unbank/loaders/List/Sections.tsx": $$$0,
  },
  "sections": {
    "deco-sites/unbank/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/unbank/sections/Theme/Theme.tsx": $$$$$$1,
  },
  "apps": {
    "deco-sites/unbank/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/unbank/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/unbank",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
